site_name: "griffe"
site_description: "Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API."
site_url: "https://mkdocstrings.github.io/griffe"
repo_url: "https://github.com/mkdocstrings/griffe"
repo_name: "mkdocstrings/griffe"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/griffe]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage:
  - CLI reference: cli_reference.md
  - Checking for API breakages: checking.md
  - Dumping data as JSON: dumping.md
  - Loading and navigating data: loading.md
  - Extensions:
    - Using and writing extensions: extensions.md
  - Docstrings:
    - Supported styles: docstrings.md
    - Parsing docstrings in Python: parsing_docstrings.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  logo: logo.svg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.sections
  - search.highlight
  - search.suggest
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/custom.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- attr_list
- callouts:
    strip_period: no
- footnotes
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
    - scripts/gen_griffe_json.py
    - scripts/redirects.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          docstring_style: google
          members_order: alphabetical
          merge_init_into_class: true
          separate_signature: true
          show_category_heading: no
          show_submodules: no

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
